---
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
  - name: ubuntu
 
verifier:
  name: terraform
  systems:
    - name: default
      backend: ssh
      user: ubuntu
      hosts_output: public_ip
      key_files: 
        - the_new_key
      controls:
      - check_pkg
      - check_string

suites:
  - name: default
